# Generated by Django 3.1.7 on 2021-03-17 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_commentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentary',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.product'),
        ),
    ]
